services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./local_db:/app/local_db
      - .:/app
    env_file: .env
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --loop uvloop --http httptools
    restart: on-failure
    depends_on:
      - redis
      - db

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: on-failure

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: africanvoices
      POSTGRES_USER: equalyzai
      POSTGRES_PASSWORD: equalyzai
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  redis_data:
  postgres_data: