"""Fix category enum spelling

Revision ID: 6b383f1a727c
Revises: fb7e3da3f5ea
Create Date: 2025-09-15 06:31:35.431833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b383f1a727c'
down_revision: Union[str, Sequence[str], None] = 'fb7e3da3f5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downloadlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloadlog',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('downloadlog_dataset_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('downloadlog_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('downloadlog_pkey'))
    )
    # ### end Alembic commands ###
