"""add new columns to datalogs

Revision ID: bbe23bddc7ba
Revises: c9df2ef2640f
Create Date: 2025-10-02 17:19:51.351457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bbe23bddc7ba'
down_revision: Union[str, Sequence[str], None] = 'c9df2ef2640f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_logs', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('download_logs', sa.Column('progress_pct', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_logs', 'progress_pct')
    op.drop_column('download_logs', 'language')
    # ### end Alembic commands ###
