"""adding more columns

Revision ID: dc3ac879d582
Revises: bbe23bddc7ba
Create Date: 2025-10-14 18:13:49.808923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dc3ac879d582'
down_revision: Union[str, Sequence[str], None] = 'bbe23bddc7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiosample', sa.Column('source', sa.VARCHAR(), nullable=True))
    op.add_column('audiosample', sa.Column('speaker_id', sa.VARCHAR(), nullable=True))
    op.add_column('audiosample', sa.Column('split', sa.VARCHAR(), nullable=True))
    op.add_column('audiosample', sa.Column('duration', sa.VARCHAR(), nullable=True))
    op.alter_column('audiosample', 'sentence_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audiosample', 'sentence',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audiosample', 'storage_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('audiosample', 'annotator_id')
    op.drop_column('audiosample', 'durations')
    op.drop_index(op.f('ix_download_logs_celery_task_id'), table_name='download_logs')
    op.drop_column('download_logs', 'total_files')
    op.drop_column('download_logs', 'celery_task_id')
    op.drop_column('download_logs', 'completed_at')
    op.drop_column('download_logs', 'started_at')
    op.drop_column('download_logs', 'total_size_bytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_logs', sa.Column('total_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('download_logs', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('download_logs', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('download_logs', sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('download_logs', sa.Column('total_files', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_download_logs_celery_task_id'), 'download_logs', ['celery_task_id'], unique=False)
    op.add_column('audiosample', sa.Column('durations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audiosample', sa.Column('annotator_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('audiosample', 'storage_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audiosample', 'sentence',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audiosample', 'sentence_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audiosample', 'duration')
    op.drop_column('audiosample', 'split')
    op.drop_column('audiosample', 'speaker_id')
    op.drop_column('audiosample', 'source')
    # ### end Alembic commands ###
